export interface MasterDetails {
    C_EndDate: string;
    C_StartDate: string;
    ClassWise: string;
    CompanyName: string;
    CompanyShortName: string;
    CountryInformationID: number;
    CountryName: string;
    Currency: string;
    CurrencyID: string;
    DecimalPoint: number;
    DepartmentID: number;
    DepartmentName: string;
    DepartmentWise: string;
    DisplayName: string;
    Email: string;
    EmployeeNo: string;
    EndDate: string;
    FirstName: string;
    IsSysAdmin: boolean;
    LastName: string;
    LocationWise: string;
    LoginID: number;
    MiddleName: string;
    PersonID: number;
    Position: string;
    StartDate: string;
    StartDayOfWeek: string;
    TenantDomain: string;
    Title: string;
    EmployeeID: any;
    EmployeeNumber: any;
    HasJournalQuestion: boolean;
    HasOpenJournal: boolean;
    HasOpenShiftLocation: boolean;
    HasSickLeave: boolean;
    DayInLieu:boolean;
    IncludeReviewerInKPIReview: boolean;
    IsEnabledLegalEntity:boolean;
    SavingSchemeHasTerm: boolean;
    SocialPermission: boolean;
    PraiseTitle: string;
    OptionalShowPhoneEmployeeCard: boolean;
  }
